restart_file: .na
start_datetime: 2024-01-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-01-08 00:00:00
forecast_horizon: 5
sim_name: GOTM
configure_flare: configure_flare_GOTM.yml
configure_obs: observation_processing.yml
use_s3: FALSE
